name: pulse proxy

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Pulse
        run: |
          if ! curl -sSLf "https://d9.goaltend.xyz/health" -o /dev/null; then
              cp M3U8/safe.m3u M3U8/base.m3u8
          fi

      - name: Replace base
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "replace base"
          file_pattern: "M3U8/base.m3u8"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
